/**
 * Export service — future: Export API (server-side PDF / DOCX rendering).
 *
 * What works in this frontend build:
 *   - Print: browser print of the court-ready preview (print stylesheet
 *     removes all application chrome).
 *   - PDF: the same print dialog, where the user chooses “Save as PDF”.
 *     No PDF file is generated by the app itself.
 *   - Word-compatible .doc: an HTML document Word can open (labelled as such).
 * Not available: true .docx generation — no DOCX library is installed, and
 * the app never writes a file with a misleading extension.
 */
import { downloadAsWordHtml } from '../utils/exportDocument';
import { readStorage, writeStorage, STORAGE_KEYS } from '../utils/storage';

export const EXPORT_CAPABILITIES = {
  print: { available: true },
  pdf: {
    available: true,
    method: 'print-dialog',
    note: 'Opens your browser’s print dialog — choose “Save as PDF” as the destination.',
  },
  docx: {
    available: false,
    reason:
      'DOCX export is not available in this build. It will be added with a DOCX generator or the Export API.',
  },
  wordHtml: {
    available: true,
    note: 'Word-compatible document (.doc, HTML-based). Formatting may differ from the preview.',
  },
};

/** Safe file name from a document title: letters, digits, spaces → dashes. */
export function buildFileName(title, extension) {
  const base =
    (title || 'legal-lens-document')
      .normalize('NFKD')
      .replace(/[^\w\- ]+/g, '')
      .trim()
      .replace(/\s+/g, '-')
      .slice(0, 80) || 'legal-lens-document';
  return extension ? `${base}.${extension}` : base;
}

/**
 * Open the browser print dialog for the current page. The page's <title> is
 * used by browsers as the default PDF file name, so it is set temporarily.
 * `bodyClass` lets the print stylesheet know what to print.
 */
export function printDocument({ title, bodyClass = 'is-printing-document' } = {}) {
  const previousTitle = document.title;
  document.title = buildFileName(title);
  document.body.classList.add(bodyClass);
  const restore = () => {
    document.title = previousTitle;
    document.body.classList.remove(bodyClass);
    window.removeEventListener('afterprint', restore);
  };
  window.addEventListener('afterprint', restore);
  window.print();
  // Some browsers do not fire afterprint reliably; restore after the dialog returns.
  setTimeout(restore, 1000);
}

export function exportWordCompatible({ title, html, lineHeight }) {
  downloadAsWordHtml({ title: buildFileName(title), html, lineHeight });
  return { ok: true };
}

export function exportDocx() {
  return { ok: false, reason: EXPORT_CAPABILITIES.docx.reason };
}

// ---------------------------------------------------------------------------
// Court-ready preview options (A4). These are layout preferences only — they
// are not a statement of any court's formatting rules.
// ---------------------------------------------------------------------------

export const A4 = { widthMm: 210, heightMm: 297 };
const PX_PER_MM = 96 / 25.4;
export const mmToPx = (mm) => mm * PX_PER_MM;

export const MARGIN_PRESETS = [
  { id: 'standard', label: 'Standard — 25 mm', top: 25, right: 25, bottom: 25, left: 25 },
  { id: 'narrow', label: 'Narrow — 19 mm', top: 19, right: 19, bottom: 19, left: 19 },
  { id: 'binding', label: 'Binding — 38 mm left', top: 25, right: 20, bottom: 25, left: 38 },
];
export const FONT_SIZES = [
  { id: '12', label: '12 pt', value: 12 },
  { id: '13', label: '13 pt', value: 13 },
  { id: '14', label: '14 pt', value: 14 },
];
export const LINE_SPACINGS = [
  { id: '1.15', label: '1.15', value: 1.15 },
  { id: '1.5', label: '1.5', value: 1.5 },
  { id: '2', label: 'Double', value: 2 },
];

export const PRINT_OPTION_DEFAULTS = {
  margins: 'standard',
  fontSize: '12',
  lineSpacing: '1.5',
  pageNumbers: true,
  footerTitle: true,
  placeholders: 'blank', // 'blank' → ________ | 'label' → [Field label]
};

/** Stored preferences merged over defaults; unknown values fall back safely. */
export function loadPrintOptions() {
  const stored = readStorage(STORAGE_KEYS.printOptions, {});
  const merged = {
    ...PRINT_OPTION_DEFAULTS,
    ...(stored && typeof stored === 'object' ? stored : {}),
  };
  if (!MARGIN_PRESETS.some((m) => m.id === merged.margins)) merged.margins = 'standard';
  if (!FONT_SIZES.some((f) => f.id === merged.fontSize)) merged.fontSize = '12';
  if (!LINE_SPACINGS.some((l) => l.id === merged.lineSpacing)) merged.lineSpacing = '1.5';
  if (!['blank', 'label'].includes(merged.placeholders)) merged.placeholders = 'blank';
  merged.pageNumbers = merged.pageNumbers !== false;
  merged.footerTitle = merged.footerTitle !== false;
  return merged;
}

export function savePrintOptions(options) {
  return writeStorage(STORAGE_KEYS.printOptions, options);
}

/** Page geometry in CSS px for a margin preset. */
export function pageGeometry(marginId) {
  const m = MARGIN_PRESETS.find((p) => p.id === marginId) ?? MARGIN_PRESETS[0];
  const width = mmToPx(A4.widthMm);
  const height = mmToPx(A4.heightMm);
  return {
    margins: m,
    width,
    height,
    contentWidth: width - mmToPx(m.left + m.right),
    contentHeight: height - mmToPx(m.top + m.bottom),
  };
}
